//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSchoolTerminal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DurationList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DurationList()
        {
            this.DrivingLessons = new HashSet<DrivingLessons>();
            this.Lessons = new HashSet<Lessons>();
        }
    
        public int DurationID { get; set; }
        public int DurationOnMinutes { get; set; }
        public string DurationOnMinutesWithWords
        {
            get
            {
                int hours = DurationOnMinutes / 60;
                int minutes = DurationOnMinutes % 60;

                string hoursSuffix = hours == 1 ? "час" : (hours >= 2 && hours <= 4 ? "часа" : "часов");
                string minutesSuffix = minutes == 1 ? "минута" : "минут";

                if (minutes == 0)
                {
                    return $"{hours} {hoursSuffix}";
                }
                else
                {
                    return $"{hours} {hoursSuffix}, {minutes} {minutesSuffix}";
                }
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrivingLessons> DrivingLessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lessons> Lessons { get; set; }
    }
}
