//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSchoolTerminal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructors()
        {
            this.DrivingLessons = new HashSet<DrivingLessons>();
            this.Lessons = new HashSet<Lessons>();
        }
    
        public int InstructorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SurName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public System.DateTime HireDate { get; set; }
        public decimal Salary { get; set; }
        public int UserID { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public string FullName
        {
            get
            {
                return LastName + " " + FirstName + " " + SurName;
            }
        }
        public string TotalWorkDate
        {
            get
            {
                int years = (int)Math.Round((DateTime.Now - HireDate).TotalDays / 365);
                return $"{years} {(years == 1 ? "год" : years >= 2 && years <= 4 ? "года" : "лет")}";
            }
        }
        public string PhotoPatch
        {
            get
            {
                return "/Resources/" + Photo;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrivingLessons> DrivingLessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lessons> Lessons { get; set; }
        public virtual Users Users { get; set; }
    }
}
